x-fern-pagination:
  offset: $request.page
  results: $response.results
paths:
  /call:
    get:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: create
  /call/{id}:
    get:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: update
  /assistant:
    get:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: create
  /assistant/{id}:
    get:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: update
  /phone-number:
    get:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: create
  /phone-number/{id}:
    get:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: update
  /squad:
    get:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: create
  /squad/{id}:
    get:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: update
  /block:
    get:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: create
  /block/{id}:
    get:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: update
  /tool:
    get:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: create
  /tool/{id}:
    get:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: update
  /file:
    get:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: create
  /file/{id}:
    get:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: get 
    delete:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: update
  /analytics:
    post:
      x-fern-sdk-group-name:
        - analytics
      x-fern-sdk-method-name: get
  /logs:
    get:
      x-fern-pagination: true
      x-fern-sdk-group-name:
        - logs
      x-fern-sdk-method-name: get
components: 
  schemas: 
    ChunkPlan: 
      properties: 
        punctuationBoundaries: 
          type: array
          enum: 
            - "。"
            - "，"
            - "."
            - "!"
            - "?"
            - ";"
            - ")"
            - "،"
            - "۔"
            - "।"
            - "॥"
            - "|"
            - "||"
            - ","
            - ":"
          x-fern-enum: 
            "。":
              name: CIRCLE
              description: "。"
            "，":
              name: FULL_WIDTH_COMMA
              description: "，"
            ".":  
              name: DOT
              description: "."
            "!":  
              name: EXCLAMATION
              description: "!"
            "?":
              name: QUESTION
              description: "?"
            ";": 
              name: SEMICOLON
              description: ";"
            ")":  
              name: PARENTHESIS
              description: ")"
            "،":
              name: ARABIC_COMMA
              description: "،"
            "۔":  
              name: URDU_FULL_STOP
              description: "۔"
            "।":  
              name: BENGALI_FULL_STOP
              description: "।"
            "॥":  
              name: DOUBLE_DANDA
              description: "॥"
            "|":  
              name: PIPE
              description: "|"
            "||": 
              name: DOUBLE_PIPE
              description: "||"
            ",":  
              name: HALF_WIDTH_COMMA
              description: ","
            ":":  
              name: COLON
              description: ":"
          example: 
            - "。"
            - "，"
            - "."
            - "!"
            - "?"
            - ";"
            - ")"
            - "،"
            - "۔"
            - "।"
            - "॥"
            - "|"
            - "||"
            - ","
            - ":"
          items: 
            type: string
            x-fern-enum: 
              "。":
                name: CIRCLE
                description: "。"
              "，":
                name: COMMA
                description: "，"
              ".":  
                name: DOT
                description: "."
              "!":  
                name: EXCLAMATION
                description: "!"
              "?":
                name: QUESTION
                description: "?"
              ";": 
                name: SEMICOLON
                description: ";"
              ")":  
                name: PARENTHESIS
                description: ")"
              "،":
                name: ARABIC_COMMA
                description: "،"
              "۔":  
                name: URDU_FULL_STOP
                description: "۔"
              "।":  
                name: BENGALI_FULL_STOP
                description: "।"
              "॥":  
                name: DOUBLE_DANDA
                description: "॥"
              "|":  
                name: PIPE
                description: "|"
              "||": 
                name: DOUBLE_PIPE
                description: "||"
              ",":  
                name: HALF_WIDTH_COMMA
                description: ","
              ":":  
                name: COLON
                description: ":"
            enum: 
              - "。"
              - "，"
              - "."
              - "!"
              - "?"
              - ";"
              - ")"
              - "،"
              - "۔"
              - "।"
              - "॥"
              - "|"
              - "||"
              - ","
              - ":"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      x-fern-bearer: 
        name: apiKey
        env: VAPI_API_KEY