name: Release all SDKs

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Go SDK that you would like to release"
        required: true
        type: string

env:
  FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
  RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  csharp:
    uses: ./.github/workflows/release-csharp-sdk.yml
    secrets: inherit
    with: 
      version: ${{ inputs.version }}
  
  go:
    uses: ./.github/workflows/release-go-sdk.yml
    secrets: inherit
    with: 
        version: ${{ inputs.version }}      

  java:
    uses: ./.github/workflows/release-java-sdk.yml
    secrets: inherit
    with: 
        version: ${{ inputs.version }}

  python:
    uses: ./.github/workflows/release-python-sdk.yml
    secrets: inherit
    with: 
        version: ${{ inputs.version }}        

  ruby:
    uses: ./.github/workflows/release-ruby-sdk.yml
    secrets: inherit
    with: 
        version: ${{ inputs.version }}   

  ts:
    uses: ./.github/workflows/release-ts-sdk.yml
    secrets: inherit
    with: 
        version: ${{ inputs.version }}           